import "./globals.css";
import type { Metadata } from "next";
import Script from "next/script"; // Script를 import

import { Pretendard, SpoqaHanSans } from "@/lib/fonts";
import DarkModeHandler from "./_components/DarkModeHandler";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head>
        <Script
          src={`https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=${process.env.NAVER_CLIENT_ID}`}
          strategy="beforeInteractive"
        />
      </head>
      <body className={`${SpoqaHanSans.className} antialiased`}>
        <DarkModeHandler />
        {children}
      </body>
    </html>
  );
}
