import "./globals.css";
import type { Metadata } from "next";

import { Pretendard, SpoqaHanSans } from "@/lib/fonts";
import DarkModeHandler from "./_components/DarkModeHandler";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${SpoqaHanSans.className} antialiased`}>
        <DarkModeHandler />
        {children}
      </body>
    </html>
  );
}
